api = "0.8"

[buildpack]
  homepage = "https://github.com/avarteqgmbh/rvm-bundler-cnb"
  id = "com.anynines.buildpacks.rvm-bundler"
  name = "RVM Buildpack for Bundler"

[metadata]
  include-files = ["bin/build","bin/detect","buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [metadata.configuration]
    default_bundler_version = "2.2.24"

    install_puma = true
    [metadata.configuration.puma]
      version = "4.3.8"
      bind = "tcp://0.0.0.0:8080"
      workers = "5"
      threads = "5"
      preload = true

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "heroku-18"
