api = "0.2"

[buildpack]
  id = "com.anynines.buildpacks.rvm-bundler"
  name = "RVM Buildpack for Bundler"
  version = "0.0.12"

[metadata]
  include-files = ["bin/build","bin/detect","buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [metadata.configuration]
    default_bundler_version = "2.1.4"

    install_puma = true
    [metadata.configuration.puma]
      version = "4.3.5"
      bind = "tcp://0.0.0.0:8080"
      workers = "5"
      threads = "5"
      preload = true

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "heroku-18"
